---

- hosts: all
  vars:
    - public_hostname: oxfam-impact-banques.telescoop.fr
    - project_slug: "oxfam-impact-banques"
    - static_path: /telescoop/oxfam-impact-banques
  remote_user: root
  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded

  tasks:
    - name: Copy nginx config
      template:
        src: nginx.conf.j2
        dest: "/etc/nginx/sites-enabled/oxfam-impact-banques"
        owner: root
        group: root
        mode: 0644
      notify:
        - reload nginx

    - name: Make sure static folder exists
      file:
        path: "{{ static_path }}"
        state: directory
        owner: www-data

    - name: Upload static files
      copy:
        src: "../{{ item }}"
        dest: "{{ static_path }}/"
        owner: www-data
      loop:
        - js
        - css
        - index.html
